// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Animal interface {
	IsAnimal()
}

type Bird struct {
	Name string `json:"name"`
	// 翅膀展開長度
	WingSpanLength int `json:"wingSpanLength"`
}

func (Bird) IsAnimal() {}

type Monkey struct {
	Name string `json:"name"`
	// 手臂展開長度
	ArmSpanLength int `json:"armSpanLength"`
}

func (Monkey) IsAnimal() {}

type Post struct {
	Published *string `json:"published"`
}

type User struct {
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}
